<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { shopApi } from '@/api/shop'
import type { Shop, ShopType } from '@/types/domain'
const route = useRoute(); const router = useRouter(); const types = ref<ShopType[]>([]); const shops = ref<Shop[]>([]); const loading = ref(false); const current = ref(1); const selectedType = ref<number | undefined>(Number(route.query.typeId) || undefined); const keyword = ref(''); const x = ref<number | undefined>(); const y = ref<number | undefined>(); const mode = ref<'type'|'name'>('type')
async function load() { loading.value = true; try { if (mode.value === 'name') shops.value = await shopApi.byName(keyword.value, current.value); else if (selectedType.value) shops.value = await shopApi.byType({ typeId: selectedType.value, current: current.value, x: x.value, y: y.value }); else shops.value = [] } finally { loading.value = false } }
function selectType(id: number) { selectedType.value = id; mode.value = 'type'; current.value = 1; void load() }
function search() { mode.value = keyword.value ? 'name' : 'type'; current.value = 1; void load() }
function next() { current.value++; void load() }
onMounted(async () => { types.value = await shopApi.types(); if (selectedType.value) await load() })
</script>
<template><div class="page-head"><div><h2>店铺中心</h2><p class="muted">分类检索每页 5 条；名称搜索每页 10 条。附近检索需 Redis GEO 数据。</p></div><el-button type="primary" @click="router.push('/shops/new')">新增店铺（开发）</el-button></div><div class="toolbar"><el-select v-model="selectedType" placeholder="选择分类" clearable style="width:180px" @change="selectType"><el-option v-for="type in types" :key="type.id" :label="type.name" :value="type.id" /></el-select><el-input v-model="keyword" clearable placeholder="按店铺名搜索" style="width:240px" @keyup.enter="search" /><el-button @click="search">搜索</el-button><el-divider direction="vertical" /><el-input-number v-model="x" :precision="6" placeholder="经度（可选）" controls-position="right" /><el-input-number v-model="y" :precision="6" placeholder="纬度（可选）" controls-position="right" /><el-button :disabled="!selectedType" @click="mode='type'; load()">附近查询</el-button></div><el-table v-loading="loading" :data="shops" stripe><el-table-column prop="id" label="ID" width="70" /><el-table-column prop="name" label="店铺名称" min-width="170" /><el-table-column prop="area" label="商圈" width="120" /><el-table-column prop="avgPrice" label="人均" width="90"><template #default="{row}">¥{{ row.avgPrice ?? '-' }}</template></el-table-column><el-table-column prop="score" label="评分" width="100"><template #default="{row}">{{ row.score ? (row.score / 10).toFixed(1) : '-' }}</template></el-table-column><el-table-column prop="distance" label="距离" width="100"><template #default="{row}">{{ row.distance ? Math.round(row.distance) + ' m' : '-' }}</template></el-table-column><el-table-column label="操作" width="150"><template #default="{row}"><el-button link type="primary" @click="router.push(`/shops/${row.id}`)">详情</el-button><el-button link @click="router.push(`/shops/${row.id}/edit`)">编辑</el-button></template></el-table-column></el-table><div class="pager"><el-button :disabled="current===1" @click="current--; load()">上一页</el-button><span>第 {{ current }} 页</span><el-button :disabled="shops.length < (mode==='type' ? 5 : 10)" @click="next">下一页</el-button></div></template>
<style scoped>.pager{display:flex;justify-content:center;gap:14px;align-items:center;margin-top:20px;font-size:13px;color:#64748b}</style>
