<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { shopApi } from '@/api/shop'
import { voucherApi } from '@/api/voucher'
import type { Shop, Voucher } from '@/types/domain'
import { splitImages, toImageUrl } from '@/utils/image'
const route = useRoute(); const router = useRouter(); const shop = ref<Shop>(); const vouchers = ref<Voucher[]>([]); const id = Number(route.params.id)
onMounted(async () => { [shop.value, vouchers.value] = await Promise.all([shopApi.get(id), voucherApi.list(id)]) })
</script>
<template><div v-if="shop"><div class="page-head"><div><h2>{{ shop.name }}</h2><p class="muted">{{ shop.address }} · {{ shop.openHours }}</p></div><el-button @click="router.push(`/shops/${id}/edit`)">编辑店铺</el-button></div><div class="grid grid-2"><el-card shadow="never"><el-carousel v-if="splitImages(shop.images).length" height="260px"><el-carousel-item v-for="image in splitImages(shop.images)" :key="image"><el-image :src="toImageUrl(image)" fit="cover" style="width:100%;height:100%" /></el-carousel-item></el-carousel><el-descriptions v-else :column="1" border><el-descriptions-item label="商圈">{{ shop.area || '-' }}</el-descriptions-item><el-descriptions-item label="地址">{{ shop.address || '-' }}</el-descriptions-item></el-descriptions><el-descriptions :column="2" border style="margin-top:16px"><el-descriptions-item label="人均">¥{{ shop.avgPrice || '-' }}</el-descriptions-item><el-descriptions-item label="评分">{{ shop.score ? shop.score/10 : '-' }}</el-descriptions-item><el-descriptions-item label="销量">{{ shop.sold || 0 }}</el-descriptions-item><el-descriptions-item label="评论">{{ shop.comments || 0 }}</el-descriptions-item></el-descriptions></el-card><el-card shadow="never"><template #header>优惠券 <el-button link @click="router.push({path:'/vouchers',query:{shopId:id}})">管理 / 秒杀</el-button></template><el-empty v-if="!vouchers.length" description="暂无优惠券" /><el-card v-for="voucher in vouchers" :key="voucher.id" class="voucher-mini" shadow="never"><b>{{ voucher.title }}</b><p>{{ voucher.subTitle || voucher.rules }}</p><strong>¥{{ voucher.payValue }} <small>抵 ¥{{ voucher.actualValue }}</small></strong><el-tag v-if="voucher.stock !== undefined" type="danger">秒杀库存 {{ voucher.stock }}</el-tag></el-card></el-card></div></div><el-skeleton v-else :rows="8" animated /></template>
<style scoped>.voucher-mini{margin-bottom:10px;background:#fff7ed}.voucher-mini p{font-size:13px;color:#64748b}.voucher-mini strong{color:#dc2626}.voucher-mini small{font-weight:400;color:#64748b}.voucher-mini .el-tag{float:right}</style>
