<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { ElMessage } from 'element-plus'
import { voucherApi } from '@/api/voucher'
import type { Voucher } from '@/types/domain'
const route=useRoute();const router=useRouter();const shopId=ref<number|undefined>(Number(route.query.shopId)||undefined);const vouchers=ref<Voucher[]>([]);const creating=ref(false);const submitting=ref<number>();const dialog=ref(false);const seckill=ref(false);const form=reactive<Voucher>({shopId:shopId.value,title:'',subTitle:'',rules:'',payValue:0,actualValue:0,type:0,status:1,stock:10,beginTime:'',endTime:''})
const title=computed(()=>shopId.value?`店铺 ${shopId.value} 的优惠券`:'请输入店铺 ID 查询优惠券')
async function load(){if(!shopId.value)return;vouchers.value=await voucherApi.list(shopId.value)}
async function create(){creating.value=true;try{form.shopId=shopId.value;const id=seckill.value?await voucherApi.createSeckill(form):await voucherApi.create(form);ElMessage.success(`优惠券已创建，ID: ${id}`);dialog.value=false;await load()}finally{creating.value=false}}
async function submit(voucher:Voucher){if(!voucher.id)return;submitting.value=voucher.id;try{const result=await voucherApi.seckill(voucher.id);ElMessage.success('秒杀请求已提交，开始查询订单状态');router.push(`/orders/${result.orderId}`)}finally{submitting.value=undefined}}
onMounted(load)
</script>
<template><div class="page-head"><div><h2>优惠券与秒杀</h2><p class="muted">新增券接口当前未鉴权；本页面仅用于本地开发测试。</p></div><el-button type="primary" @click="dialog=true">创建优惠券（开发）</el-button></div><div class="toolbar"><el-input-number v-model="shopId" :min="1" placeholder="店铺 ID"/><el-button @click="load">查询</el-button><span class="muted">{{title}}</span></div><el-empty v-if="shopId&&!vouchers.length" description="该店铺暂无优惠券" /><div class="grid grid-3"><el-card v-for="voucher in vouchers" :key="voucher.id" shadow="never" class="voucher"><el-tag :type="voucher.stock === undefined?'info':'danger'">{{voucher.stock === undefined?'普通券':'秒杀券'}}</el-tag><h3>{{voucher.title}}</h3><p>{{voucher.subTitle||voucher.rules||'暂无使用规则'}}</p><div class="price">¥{{voucher.payValue}} <small>抵 ¥{{voucher.actualValue}}</small></div><p v-if="voucher.stock !== undefined" class="muted">库存 {{voucher.stock}} · {{voucher.beginTime}} 至 {{voucher.endTime}}</p><el-button v-if="voucher.stock !== undefined" type="danger" :loading="submitting===voucher.id" @click="submit(voucher)">提交秒杀</el-button></el-card></div><el-dialog v-model="dialog" title="创建优惠券（开发接口）" width="620px"><el-form :model="form" label-width="100px"><el-form-item label="秒杀券"><el-switch v-model="seckill" /></el-form-item><el-form-item label="标题"><el-input v-model="form.title" /></el-form-item><el-form-item label="副标题"><el-input v-model="form.subTitle" /></el-form-item><el-form-item label="规则"><el-input v-model="form.rules" /></el-form-item><el-form-item label="支付 / 抵扣"><el-input-number v-model="form.payValue" :min="0" /><span class="between">/</span><el-input-number v-model="form.actualValue" :min="0" /></el-form-item><template v-if="seckill"><el-form-item label="库存"><el-input-number v-model="form.stock" :min="1" /></el-form-item><el-form-item label="开始时间"><el-date-picker v-model="form.beginTime" type="datetime" value-format="YYYY-MM-DDTHH:mm:ss" /></el-form-item><el-form-item label="结束时间"><el-date-picker v-model="form.endTime" type="datetime" value-format="YYYY-MM-DDTHH:mm:ss" /></el-form-item></template></el-form><template #footer><el-button @click="dialog=false">取消</el-button><el-button type="primary" :loading="creating" @click="create">创建</el-button></template></el-dialog></template>
<style scoped>.voucher h3{margin:14px 0 8px}.voucher p{font-size:13px;color:#64748b;min-height:20px}.price{font-size:24px;font-weight:700;color:#dc2626;margin:16px 0}.price small{font-weight:400;font-size:13px;color:#64748b}.between{margin:0 10px}</style>
